====================================
 Testing 'lazy_matrix_mul' Function
====================================

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

>>> lazy_matrix_mul([[4], [5]])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> lazy_matrix_mul(4, [4, 5])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([4, 5], 'list')
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([[4, 5]], [4, 6, 8])
Traceback (most recent call last):
ValueError: shapes (1,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

>>> lazy_matrix_mul([1, 2, 3], [[2, 1], [7, 5]])
Traceback (most recent call last):
ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

>>> lazy_matrix_mul([], [[2, 1], [7, 5]])
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

>>> lazy_matrix_mul([[2, 1], [7, 5]], [])
Traceback (most recent call last):
ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

>>> lazy_matrix_mul([[2.3, 21], ['3', 'd']], [[2, 1], [7, 5]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[2, 1], [7, 5]], [[2.3, 21], ['3', 'd']])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[2, 1], [7, 5, 7]], [[2.3, 21], [3, 4]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[2.3, 21], [3, 4]], [[2, 1], [7, 5, 8]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[2.3], [4]], [[2, 1], [5, 7]])
Traceback (most recent call last):
ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)
